RAC_machines = [
    "3x concept2 ergs",
    "7x recumbent bike", 
    "13x elliptical",
    "12x treadmill",
    "4x indoor bike",
    "8x bences",
    "3x dumbbell rack",
    "1x ez bar rack",
    "1x ab bench",
    "1x decline ab bench", 
    "2x power tower",
    "1x stair master",
    "1x plate loaded squat machine",
    "1x hip abduction machine",
    "1x non adjustable upright bench seat",
    "1x incline bench w/ barbell",
    "3x bench w/ barbell", 
    "1x decline bench w/ barbell",
    "1x pec deck", 
    "1x lat pull-down", 
    "1x converging shoulder press", 
    "1x assisted dip machine", 
    "1x diverging low row",
    "1x abdominal crunch", 
    "1x back extension",
    "2x cable machine", 
    "1x triceps extension",  
    "1x bicep curl machine",
    "1x converging chest press", 
    "1x leg press", 
    "1x leg curl", 
    "1x preacher curl bench", 
    "2x deadlift pad", 
    "4x squat rack", 
    "1x back hyperextension bench",
    "Basketball court"
]

SKY_machines = [
    "4x squat racks",
    "2x beaches",
    "1x leg press", 
    "5x adjustable dumbbell benches",
    "1x non-adjustable dumbbell benches",
    "1x hip extension machine", 
    "1x pull machine", 
    "1x dip machine",
    "Straight curl bars", 
    "8x treadmills", 
    "1x hip thrust machine", 
    "1x leg extension",
    "1x weighted pull up machine", 
    "1x weighted dips machine",
    "1x seated row machine", 
    "1x lay machine", 
    "1x leg curl machine", 
    "1x squat machine", 
    "1x leg press machine", 
    "2x big workout stations", 
    "1x calf extension machines", 
    "1x shoulder press machine", 
    "1x back extension machine",
    "1x abdominal machine", 
    "1x bicep curl machine", 
    "1x tricep machine", 
    "1x chest press machine", 
    "1x prone leg curl machine", 
    "7x cardio cycle machine", 
    "8x cardio pedal machine", 
    "Rock climber station",
    "Dumbbells up to 100lbs",
    "Yoga Mats", 
    "Yoga balls", 
    "Basketball court", 

]

AFC_machines = [
	"2x Cable machine",
	"1x T-bar",
	"3x Bench",
	"1x Squat rack",
	"1x Decline bench",
	"Dumbbells up to 120 lbs",
	"Curl bars up to 120 lbs",
	"Straight bars up to 120 lbs",
	"1x Smith machine",
	"1x Pull up and cables machine set",
	"1x Weighted dib machine",
	"1x Weighted pullup machine",
	"1x Deck fly machine",
	"1x Rear fly machine",
	"1x Leg press",
	"2x Lat pull down",
	"1x Leg extension",
	"1x Leg curl",
    "1x Bicep curl machine",
	"2x Treadmills",
	"2x Stair masters",
	"2x Cycle machines"
]