#use these for all pieces 
list = [
    "Never out of the fight.",
    "The only easy day was yesterday.",
    "Job town.",
    "Pay the man.",
    "Never a fair fight.",
    "Like your life depends on it.",
    "Complacency kills.",
    "Train how you fight.",
    "To be, rather than to seem.",
    "Loyal to the mission.",
    "Fortune favors the bold.",
    "Whatever it takes.",
    "He who conquers himself is mighty.",
    "All the way.",
    "No half measures.",
    "Always forward.",
    "Sua Sponte.",
    "Earn it.",
    "Be somebody.",
    "Interior attack.", 
    "Be an asset, not a liability.",
    "HIHFTY",
    "Of your own accord.",
    "Waste no more time arguing about what a good man should be. Be one.",
    "It is not death that a man should fear, but he should fear never beginning to live.",
    "What disgrace to grow old through sheer carelessness before seeing what manner of man you may become by developing your bodily strength and beauty to their highest limit.",
    "'We are privileged to live another day in this magnificent world. Today you will be tested.' -Mike Livingston",
    "'Somewhere in the race, you will find out what it is you've been working for...and when the right answers are coming back, it's a feeling you know you will never forget.' -Dan Topolski",
    "'Yonder are the Hessians. They were bought for seven pounds and tenpence a man. Are you worth more? Prove it.' - General John Stark, Battle of Bennington 1777",
    "'Tonight the American flag floats from yonder hill or Molly Stark sleeps a widow!.' - General John Stark, Battle of Bennington 1777",
    "Put 'em on safe and let 'em hang.",
    "Keep your feet on the ground.",
    "How can man die better, than facing fearful odds, for the ashes of his fathers, and the temples of his Gods.", 
    "'I have not yet begun to fight.' -Captain John Paul Jones in response to a demand for his surrender, 1779",
    "'Hard pressed on my right. My center is yielding. Impossible to maneuver. Situation excellent. I am attacking.' -General Ferdinand Foch, Battle of the Marne 1914",
    "'We hold these truths to be self-evident, that all men are created equal, that they are endowed by their Creator with certain unalienable Rights, that among these are Life, Liberty and the pursuit of Happiness...'",
    "'Perseverance and Spirit have done Wonders in all ages.' -General George Washington, 1775",
    "'Little strokes fell great oaks.' -Benjamin Franklin, 1750",
    "'We fight, get beat, rise, and fight again.' -General Nathanael Greene, 1781",
    "'Live free or die: death is not the worst of evils.' -General John Stark, 1809",
    "'The harder the conflict, the more glorious the triumph.' -Thomas Paine",
    
]

#use these for the active recovery pieces 
recovery = [
    "Keep it light.",
    "Taking it easy.",
    "Get yourself ready for the hard part.",
    "Don't empty the tank yet.",
    "Don't get complacent.",
    "Keep yourself moving.",
    "Heart rate down.",
    "Make it look easy.",
]

#use these for erg pieces
row = [
    "Drive with the legs.",
    "Quick catches.",
    "Push them away.",
    "Arms down and away.",
    "Don't let them walk on you.",
    "Make it look easy.",
    "Eyes in the boat.",
    "Make it burn.",
    "Pry us forward.",
    "Own the water.",
    "Hunt 'em down.",
    "Power 10 in 2.",
    "Leave 'em in the dust.",
    "Show 'em how you do it.",
    "How badly do you want it?",
    "Sharp blades, sharp catches.",
    "Stay dynamic.",
    "Heads up, eyes straight.",
    "You're on!",
]
